import { Database } from "../types/supabase";

export const MOCK_TIER_LIST: Database['public']['Tables']['commission_tiers']['Row'][] = [
    {
        id: "1",
        category: "Tier 1",
        price_php: 10,
        price_usd: 10,
        description: "Tier 1 description",
        is_active: true,
        slot_limit: 1,
        thumbnail_url: "https://via.placeholder.com/150",
        variant: "Variant 1",
        created_at: '2026-02-02T14:32:59.000Z',
    },
    {
        id: "2",
        category: "Tier 2",
        price_php: 20,
        price_usd: 20,
        description: "Tier 2 description",
        is_active: true,
        slot_limit: 1,
        thumbnail_url: "https://via.placeholder.com/150",
        variant: "Variant 2",
        created_at: '2026-02-02T14:32:59.000Z',
    },
    {
        id: "3",
        category: "Tier 3",
        price_php: 30,
        price_usd: 30,
        description: "Tier 3 description",
        is_active: true,
        slot_limit: 1,
        thumbnail_url: "https://via.placeholder.com/150",
        variant: "Variant 3",
        created_at: '2026-02-02T14:32:59.000Z',
    },
    {
        id: "4",
        category: "Tier 4",
        price_php: 40,
        price_usd: 40,
        description: "Tier 4 description",
        is_active: true,
        slot_limit: 1,
        thumbnail_url: "https://via.placeholder.com/150",
        variant: "Variant 4",
        created_at: '2026-02-02T14:32:59.000Z',
    },
    {
        id: "5",
        category: "Tier 5",
        price_php: 50,
        price_usd: 50,
        description: "Tier 5 description",
        is_active: true,
        slot_limit: 1,
        thumbnail_url: "https://via.placeholder.com/150",
        variant: "Variant 5",
        created_at: '2026-02-02T14:32:59.000Z',
    },
    {
        id: "6",
        category: "Tier 6",
        price_php: 60,
        price_usd: 60,
        description: "Tier 6 description",
        is_active: true,
        slot_limit: 1,
        thumbnail_url: "https://via.placeholder.com/150",
        variant: "Variant 6",
        created_at: '2026-02-02T14:32:59.000Z',
    },
    {
        id: "7",
        category: "Tier 7",
        price_php: 70,
        price_usd: 70,
        description: "Tier 7 description",
        is_active: true,
        slot_limit: 1,
        thumbnail_url: "https://via.placeholder.com/150",
        variant: "Variant 7",
        created_at: '2026-02-02T14:32:59.000Z',
    },
    {
        id: "8",
        category: "Tier 8",
        price_php: 80,
        price_usd: 80,
        description: "Tier 8 description",
        is_active: true,
        slot_limit: 1,
        thumbnail_url: "https://via.placeholder.com/150",
        variant: "Variant 8",
        created_at: '2026-02-02T14:32:59.000Z',
    },
    {
        id: "9",
        category: "Tier 9",
        price_php: 90,
        price_usd: 90,
        description: "Tier 9 description",
        is_active: true,
        slot_limit: 1,
        thumbnail_url: "https://via.placeholder.com/150",
        variant: "Variant 9",
        created_at: '2026-02-02T14:32:59.000Z',
    },
    {
        id: "10",
        category: "Tier 10",
        price_php: 100,
        price_usd: 100,
        description: "Tier 10 description",
        is_active: true,
        slot_limit: 1,
        thumbnail_url: "https://via.placeholder.com/150",
        variant: "Variant 10",
        created_at: '2026-02-02T14:32:59.000Z',
    },
]